services:
  code-server:
    build: .
    container_name: code-server
    environment:
      - TZ=Asia/Shanghai
      - PASSWORD=cc9d5d9b82a7fc
    volumes:
      - /volume7/docker/codeserver/config:/home/coder/.config
      - /volume7/docker/codeserver/projects:/home/coder/project
      - /volume7/docker/codeserver/config/code-server-data:/home/coder/.local/share/code-server
    ports:
      - '127.0.0.1:8686:8080'
      - '0.0.0.0:25252:8080'
      - '0.0.0.0:9876:9876'
      - '0.0.0.0:8420:8420'
    restart: unless-stopped
